export const DAILY_VOLUME = {
  NEW_VOCAB_CARDS: 12,
  SENTENCE_CARDS: 4,
  REVIEW_CARDS: 8,
  TOTAL_FLASHCARDS: 24,
  CONVERSATION_MIN_TURNS: 8,
  READING_MIN_WORDS: 400,
  READING_MAX_WORDS: 450,
  READING_CORE_QUESTIONS: 6,
  READING_ADAPTIVE_QUESTIONS: 6,
  READING_TOTAL_QUESTIONS: 12,
  WRITING_MIN_WORDS: 180,
  WRITING_MAX_WORDS: 220,
  ERROR_REVIEW_ITEMS: 5,
} as const;

export type DailyVolumeKey = keyof typeof DAILY_VOLUME;
